// <auto-generated />
using System;
using Hotel.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel.Server.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231223152002_Add_Roomtype_RtDes1")]
    partial class Add_Roomtype_RtDes1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Booking", b =>
                {
                    b.Property<int>("BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("B_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BId"));

                    b.Property<decimal?>("BAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("B_Amount");

                    b.Property<DateTime?>("BCheckingDate")
                        .HasColumnType("date")
                        .HasColumnName("B_CheckingDate");

                    b.Property<DateTime?>("BCheckoutDate")
                        .HasColumnType("date")
                        .HasColumnName("B_CheckoutDate");

                    b.Property<decimal?>("BCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("B_Cost");

                    b.Property<DateTime?>("BDate")
                        .HasColumnType("date")
                        .HasColumnName("B_DATE");

                    b.Property<string>("BStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("B_Status");

                    b.Property<int?>("BStayDuration")
                        .HasColumnType("int")
                        .HasColumnName("B_StayDuration");

                    b.Property<int?>("DId")
                        .HasColumnType("int")
                        .HasColumnName("D_ID");

                    b.Property<int?>("EId")
                        .HasColumnType("int")
                        .HasColumnName("E_ID");

                    b.Property<int?>("GId")
                        .HasColumnType("int")
                        .HasColumnName("G_ID");

                    b.Property<int?>("HId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    b.Property<int?>("Rid")
                        .HasColumnType("int");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BId")
                        .HasName("PK__BOOKING__4B26EFE62E59BE7A");

                    b.HasIndex("Rid");

                    b.HasIndex(new[] { "DId" }, "IX_BOOKING_D_ID");

                    b.HasIndex(new[] { "EId" }, "IX_BOOKING_E_ID");

                    b.HasIndex(new[] { "GId" }, "IX_BOOKING_G_ID");

                    b.HasIndex(new[] { "HId" }, "IX_BOOKING_H_ID");

                    b.ToTable("BOOKING", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Department", b =>
                {
                    b.Property<int>("DeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeId"));

                    b.Property<string>("DeDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DE_Description");

                    b.Property<decimal?>("DeInitialSalary")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DE_InitialSalary");

                    b.Property<string>("DeName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DE_Name");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeId")
                        .HasName("PK__DEPARTME__F2DD468775278C67");

                    b.ToTable("DEPARTMENT", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Discount", b =>
                {
                    b.Property<int>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("D_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DId"));

                    b.Property<string>("DDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("D_Description");

                    b.Property<string>("DName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("D_Name");

                    b.Property<decimal?>("DRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("D_Rate");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DId")
                        .HasName("PK__DISCOUNT__76B8FF7D48D2F315");

                    b.ToTable("DISCOUNT", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("E_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<int?>("DeId")
                        .HasColumnType("int")
                        .HasColumnName("DE_ID");

                    b.Property<string>("EAddress")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("E_Address");

                    b.Property<string>("EContactNumber")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("E_ContactNumber");

                    b.Property<string>("EDesignation")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("E_Designation");

                    b.Property<string>("EEmail")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("E_Email");

                    b.Property<string>("EFirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("E_FirstName");

                    b.Property<DateTime?>("EJoinDate")
                        .HasColumnType("date")
                        .HasColumnName("E_JoinDate");

                    b.Property<string>("ELastName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("E_LastName");

                    b.Property<int?>("HId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EId")
                        .HasName("PK__EMPLOYEE__D730AF543A07B3C3");

                    b.HasIndex("DeId");

                    b.HasIndex("HId");

                    b.ToTable("EMPLOYEE", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Feedback", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("F_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FId"));

                    b.Property<int?>("BId")
                        .HasColumnType("int")
                        .HasColumnName("B_ID");

                    b.Property<DateTime?>("FDate")
                        .HasColumnType("date")
                        .HasColumnName("F_Date");

                    b.Property<string>("FDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("F_Description");

                    b.Property<int?>("FRate")
                        .HasColumnType("int")
                        .HasColumnName("F_Rate");

                    b.Property<int?>("GId")
                        .HasColumnType("int")
                        .HasColumnName("G_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FId")
                        .HasName("PK__FEEDBACK__2C6EC7C379E7FF2F");

                    b.HasIndex("BId");

                    b.HasIndex("GId");

                    b.ToTable("FEEDBACK", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Guest", b =>
                {
                    b.Property<int>("GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("G_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GId"));

                    b.Property<string>("GAccount")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("G_Account");

                    b.Property<string>("GCccd")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("G_CCCD");

                    b.Property<string>("GEmail")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("G_Email");

                    b.Property<string>("GFirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("G_FirstName");

                    b.Property<string>("GLastName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("G_LastName");

                    b.Property<string>("GSdt")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("G_SDT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GId")
                        .HasName("PK__GUEST__153A8ED2E509F5A5");

                    b.ToTable("GUEST", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Hotel1", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HId"));

                    b.Property<string>("HAddress")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("H_Address");

                    b.Property<string>("HDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("H_Description");

                    b.Property<string>("HEmail")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("H_Email");

                    b.Property<int?>("HFloorCount")
                        .HasColumnType("int")
                        .HasColumnName("H_FloorCount");

                    b.Property<string>("HName")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("H_Name");

                    b.Property<string>("HSdt")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("H_SDT");

                    b.Property<int?>("HTotalRoom")
                        .HasColumnType("int")
                        .HasColumnName("H_TotalRoom");

                    b.Property<string>("HWebsite")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("H_Website");

                    b.Property<string>("HZip")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("H_ZIP");

                    b.HasKey("HId")
                        .HasName("PK__HOTEL__61F3893D4FB0689A");

                    b.ToTable("HOTEL", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Payment", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("P_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"));

                    b.Property<int?>("BId")
                        .HasColumnType("int")
                        .HasColumnName("B_ID");

                    b.Property<decimal?>("PAmout")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("P_Amout");

                    b.Property<DateTime?>("PDatCoc")
                        .HasColumnType("date")
                        .HasColumnName("P_DatCoc");

                    b.Property<string>("PStatus")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Status");

                    b.Property<string>("PType")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("P_Type");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime")
                        .HasColumnName("PaidDate");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PId")
                        .HasName("PK__PAYMENT__A3420A77DE9AEC7C");

                    b.HasIndex("BId");

                    b.ToTable("PAYMENT", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Room", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("R_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RId"));

                    b.Property<string>("RAvailable")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("R_Available");

                    b.Property<string>("RNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("R_Number");

                    b.Property<int?>("RtId")
                        .HasColumnType("int")
                        .HasColumnName("RT_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RId")
                        .HasName("PK__ROOM__DE152E89CDA1DB90");

                    b.HasIndex(new[] { "RtId" }, "IX_ROOM_RT_ID");

                    b.ToTable("ROOM", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.RoomImg", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImgURL");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RoomImg__3214EC076EFE77A3");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImg", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Roomtype", b =>
                {
                    b.Property<int>("RtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RtId"));

                    b.Property<decimal?>("RArea")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("R_Area");

                    b.Property<decimal?>("RtCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RT_Cost");

                    b.Property<string>("RtDes")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RT_DES");

                    b.Property<string>("RtDes1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RtName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RT_NAME");

                    b.Property<string>("RtSmokeFriendly")
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RT_SmokeFriendly");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RtId")
                        .HasName("PK__ROOMTYPE__4056367E2D56CACE");

                    b.ToTable("ROOMTYPE", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Salary_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryId"));

                    b.Property<int?>("EId")
                        .HasColumnType("int")
                        .HasColumnName("E_ID");

                    b.Property<decimal?>("Salary1")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Salary");

                    b.Property<DateTime?>("SalaryDate")
                        .HasColumnType("date")
                        .HasColumnName("Salary_Date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SalaryId")
                        .HasName("PK__SALARY__D64E0E24600A4D58");

                    b.HasIndex("EId");

                    b.ToTable("SALARY", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Service", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("S_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<decimal?>("SCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("S_Cost");

                    b.Property<string>("SDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("S_Description");

                    b.Property<string>("SName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("S_Name");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SId")
                        .HasName("PK__SERVICES__A3DFF16D6E06E772");

                    b.ToTable("SERVICES", (string)null);
                });

            modelBuilder.Entity("Hotel.Shared.Models.Servicesbooked", b =>
                {
                    b.Property<int>("SId")
                        .HasColumnType("int")
                        .HasColumnName("S_ID");

                    b.Property<int>("BId")
                        .HasColumnType("int")
                        .HasColumnName("B_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SId", "BId")
                        .HasName("PK__SERVICES__D76D9F93DCA2E309");

                    b.HasIndex("BId");

                    b.ToTable("SERVICESBOOKED", (string)null);
                });

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.HasOne("Hotel.Shared.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.Shared.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("Hotel.Shared.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("Hotel.Shared.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("Hotel.Shared.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUserToken", b =>
                {
                    b.HasOne("Hotel.Shared.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Booking", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Discount", "DIdNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("DId")
                        .HasConstraintName("FK__BOOKING__D_ID__75A278F5");

                    b.HasOne("Hotel.Shared.Models.Employee", "EIdNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("EId")
                        .HasConstraintName("FK__BOOKING__E_ID__73BA3083");

                    b.HasOne("Hotel.Shared.Models.Guest", "GIdNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("GId")
                        .HasConstraintName("FK__BOOKING__G_ID__74AE54BC");

                    b.HasOne("Hotel.Shared.Models.Hotel1", "HIdNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("HId")
                        .HasConstraintName("FK__BOOKING__H_ID__72C60C4A");

                    b.HasOne("Hotel.Shared.Models.Room", "RidNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("Rid")
                        .HasConstraintName("FK__BOOKING__Rid__01142BA1");

                    b.Navigation("DIdNavigation");

                    b.Navigation("EIdNavigation");

                    b.Navigation("GIdNavigation");

                    b.Navigation("HIdNavigation");

                    b.Navigation("RidNavigation");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Employee", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Department", "De")
                        .WithMany("Employees")
                        .HasForeignKey("DeId")
                        .HasConstraintName("FK__EMPLOYEE__DE_ID__6D0D32F4");

                    b.HasOne("Hotel.Shared.Models.Hotel1", "HIdNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("HId")
                        .HasConstraintName("FK__EMPLOYEE__H_ID__6E01572D");

                    b.Navigation("De");

                    b.Navigation("HIdNavigation");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Feedback", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Booking", "BIdNavigation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BId")
                        .HasConstraintName("FK__FEEDBACK__B_ID__08B54D69");

                    b.HasOne("Hotel.Shared.Models.Guest", "GIdNavigation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("GId")
                        .HasConstraintName("FK__FEEDBACK__G_ID__07C12930");

                    b.Navigation("BIdNavigation");

                    b.Navigation("GIdNavigation");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Payment", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Booking", "BIdNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("BId")
                        .HasConstraintName("FK__PAYMENT__B_ID__02084FDA");

                    b.Navigation("BIdNavigation");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Room", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Roomtype", "Rt")
                        .WithMany("Rooms")
                        .HasForeignKey("RtId")
                        .HasConstraintName("FK__ROOM__RT_ID__68487DD7");

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("Hotel.Shared.Models.RoomImg", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Roomtype", "Room")
                        .WithMany("RoomImgs")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__RoomImg__RoomId__160F4887");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Salary", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Employee", "EIdNavigation")
                        .WithMany("Salaries")
                        .HasForeignKey("EId")
                        .HasConstraintName("FK__SALARY__E_ID__04E4BC85");

                    b.Navigation("EIdNavigation");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Servicesbooked", b =>
                {
                    b.HasOne("Hotel.Shared.Models.Booking", "BIdNavigation")
                        .WithMany("Servicesbookeds")
                        .HasForeignKey("BId")
                        .IsRequired()
                        .HasConstraintName("FK__SERVICESBO__B_ID__7F2BE32F");

                    b.HasOne("Hotel.Shared.Models.Service", "SIdNavigation")
                        .WithMany("Servicesbookeds")
                        .HasForeignKey("SId")
                        .IsRequired()
                        .HasConstraintName("FK__SERVICESBO__S_ID__7E37BEF6");

                    b.Navigation("BIdNavigation");

                    b.Navigation("SIdNavigation");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("Hotel.Shared.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Booking", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Payments");

                    b.Navigation("Servicesbookeds");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Discount", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Employee", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Guest", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Hotel1", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Roomtype", b =>
                {
                    b.Navigation("RoomImgs");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Hotel.Shared.Models.Service", b =>
                {
                    b.Navigation("Servicesbookeds");
                });
#pragma warning restore 612, 618
        }
    }
}
